server:
  port: 9090


spring:
  application:
    name: QUESTION-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  eureka:
    instance:
      client:
        serverUrl:
          defaultZone: http://localhost:8761/eureka/

